const project = {
  "title": "Gestionnaire de Tâches — Todo App",
  "instructions": "# Gestionnaire de Tâches — Todo App\n\n## Objectif\n\nCréer une application complète de gestion de tâches (Todo App) en Vue.js 3 utilisant le Composition API, le stockage local (localStorage) et un thème sombre/clair.\n\n---\n\n## Consignes\n\n### 1. Fonctionnalités principales (CRUD)\n\n- **Ajouter** une tâche avec un titre (obligatoire, min. 2 caractères)\n- **Afficher** la liste de toutes les tâches\n- **Modifier** le titre d'une tâche en double-cliquant dessus (édition inline)\n- **Supprimer** une tâche avec confirmation\n- **Marquer** une tâche comme terminée (cocher/décocher)\n- **Filtrer** les tâches par statut : Toutes, En cours, Terminées\n\n### 2. Système de Catégories\n\n- Chaque tâche peut avoir une **catégorie** : Travail, Personnel, Études, Loisirs\n- Filtrer les tâches par catégorie\n- Afficher un compteur de tâches par catégorie\n- Les catégories doivent avoir des couleurs distinctes\n\n### 3. Persistance des Données (localStorage)\n\n- Sauvegarder automatiquement les tâches dans le `localStorage`\n- Charger les tâches au démarrage de l'application\n- Créer un composable `useLocalStorage` réutilisable\n\n### 4. Thème Sombre / Clair\n\n- Un bouton toggle pour basculer entre thème clair et sombre\n- Utiliser le composable `useTheme` gérant un `provide/inject` ou un store\n- Préférer la préférence système par défaut (`prefers-color-scheme`)\n- Appliquer le thème à toute l'application via des variables CSS\n\n### 5. Composants à créer\n\n- **App.vue** : layout principal avec header et footer\n- **TodoForm.vue** : formulaire d'ajout de tâche\n- **TodoList.vue** : conteneur de la liste\n- **TodoItem.vue** : un élément de la liste (édition, suppression, toggle)\n- **TodoFilter.vue** : barre de filtrage (statut + catégorie)\n- **ThemeToggle.vue** : bouton de bascule thème\n\n### 6. Composables à créer\n\n- `useLocalStorage(key, valeurInitiale)` : synchronise une ref avec le localStorage\n- `useTheme()` : gère le thème clair/sombre avec persistance\n\n---\n\n## Contraintes techniques\n\n- Vue.js 3 avec `<script setup>`\n- Composition API uniquement (pas d'Options API)\n- TypeScript obligatoire\n- Pas de bibliothèque externe de state management (pas de Pinia/Vuex)\n- CSS custom (variables CSS pour le thème)\n- Les tâches doivent être générées avec des IDs uniques (`crypto.randomUUID()` ou similaire)\n\n---\n\n## Rendu\n\nDéposer le code source sur GitHub et soumettre le lien du repository.",
  "evaluationCriteria": [
    "Fonctionnalités CRUD complètes (ajouter, modifier, supprimer, marquer terminé)",
    "Système de catégories fonctionnel avec filtrage et compteurs",
    "Persistance localStorage via composable personnalisé",
    "Thème sombre/clair avec préférence système détectée",
    "Architecture (composables réutilisables, découpage en composants, TypeScript)"
  ]
};

export default project;
