const project = {
  "title": "Cluster Docker Swarm avec Monitoring et CI/CD",
  "instructions": "# Cluster Docker Swarm avec Monitoring et CI/CD\n\n## Objectif\n\nDéployer une application web sur un cluster Docker Swarm avec monitoring complet, logging centralisé et pipeline CI/CD automatisé.\n\n## Consignes\n\n### 1. Cluster Docker Swarm\n\n- Initialiser un cluster Swarm avec 1 manager et 2 workers (simulés via Docker Desktop ou VMs)\n- Définir une stack Docker Compose pour le déploiement Swarm (docker stack deploy)\n- Configurer 3 réplicas du service API avec rolling update (order: start-first)\n- Ajouter un service Nginx comme reverse proxy avec healthcheck\n- Tester le scaling : docker service scale api=5 puis revenir à 3\n\n### 2. Monitoring avec Prometheus et Grafana\n\n- Déployer cAdvisor pour la collecte de métriques conteneurs\n- Déployer Prometheus avec un fichier de configuration scrape (cAdvisor + Docker daemon)\n- Déployer Grafana avec un datasource Prometheus pré-configuré\n- Créer un dashboard Grafana montrant : CPU par conteneur, mémoire, réseau, bloc I/O\n- Ajouter un healthcheck sur chaque service dans docker-stack.yml\n\n### 3. Logging avec ELK Stack\n\n- Déployer Elasticsearch (single-node pour le dev)\n- Déployer Logstash avec un pipeline de configuration (input Docker, filter JSON, output ES)\n- Déployer Kibana avec connexion à Elasticsearch\n- Configurer les conteneurs pour envoyer leurs logs stdout vers Logstash via le driver de log json-file\n\n### 4. CI/CD avec GitHub Actions\n\n- Créer un workflow GitHub Actions qui : build l'image Docker multi-stage, lève Trivy pour le scan de vulnérabilités, pousse l'image vers GHCR, déploie sur le cluster Swarm via SSH\n- Utiliser Docker Buildx avec le cache GitHub Actions (cache-from/cache-to type=gha)\n- Taguer les images avec le SHA du commit (pas :latest)\n\n### 5. Sécurité\n\n- Les conteneurs API et Nginx tournent avec un utilisateur non-root\n- Les secrets (DB password) sont gérés via Docker Secrets (pas de variables d'environnement)\n- Un .dockerignore exclut node_modules, .git, .env\n- Le Dockerfile utilise des images Alpine minimales\n\n## Contraintes techniques\n\n- Toute l'infrastructure est définie en YAML (docker-stack.yml + docker-compose.yml pour le monitoring)\n- L'API doit être en TypeScript avec multi-stage build\n- Le pipeline CI/CD doit être fonctionnel (GitHub Actions)\n- Les dashboards Grafana doivent montrer des métriques en temps réel\n\n## Livrables\n\n1. Répertoire Git complet avec Dockerfile, docker-stack.yml, docker-compose-monitoring.yml\n2. Fichiers de configuration : prometheus.yml, logstash.conf, nginx.conf\n3. Workflow GitHub Actions : .github/workflows/ci-cd.yml\n4. README.md décrivant l'architecture, le déploiement et l'accès aux outils\n5. Capture d'écran du dashboard Grafana et de Kibana avec données réelles",
  "evaluationCriteria": [
    "Cluster Swarm fonctionnel (docker stack deploy, rolling update, scaling, healthcheck)",
    "Monitoring opérationnel (Prometheus scrape cAdvisor, Grafana dashboard avec métriques réelles)",
    "Pipeline CI/CD complet (GitHub Actions build, scan Trivy, push GHCR, deploy Swarm)",
    "Sécurité des conteneurs (utilisateur non-root, Docker Secrets, .dockerignore, images Alpine)",
    "Logging centralisé (ELK stack fonctionnel avec logs d'application dans Kibana)"
  ]
};

export default project;
