import { Level } from '@prisma/client';

export const reactNativeAdvanced = {
  techSlug: "react-native",
  title: "React Native Avancé",
  description: "Animations fluides, performance optimale, mode hors-ligne et déploiement professionnel d'applications React Native.",
  level: Level.advanced,
  durationMin: 300,
  lessons: [
  {
    "title": "Animations et Gestes",
    "durationMin": 80,
    "contentMarkdown": "# Animations et Gestes\n\n## Introduction\n\nLes animations et la gestion des gestes sont essentielles pour créer une expérience utilisateur fluide et naturelle dans une application React Native.\n\n## 1. React Native Reanimated 3\n\nReanimated 3 exécute les animations sur le thread UI au lieu du thread JS, garantissant des animations à 60fps même lorsque le thread JS est occupé.\n\n## 2. Gesture Handler\n\nGesture Handler remplace le système de gestes natif de React Native pour offrir des interactions plus fluides : tap, swipe, pinch, rotation, long press.\n\n## 3. Animations d'écran\n\nUtilisez react-navigation avec les transitions personnalisées pour créer des animations fluides entre les écrans.\n\n## 4. Performance des animations\n\nUtilisez useAnimatedStyle, useSharedValue et withSpring/withTiming pour des animations performantes sans re-rendu inutile.\n\n## Résumé\n\n- Reanimated 3 : animations sur le thread UI\n- Gesture Handler : gestes natifs fluides\n- Transitions d'écran personnalisées\n- useSharedValue, useAnimatedStyle, withSpring"
  },
  {
    "title": "Performance et Optimisation",
    "durationMin": 75,
    "contentMarkdown": "# Performance et Optimisation\n\n## Introduction\n\nLes performances sont cruciales pour la rétention des utilisateurs mobiles. Une app React Native bien optimisée se lance rapidement, défile sans à-coups et consomme peu de batterie.\n\n## 1. Hermes Engine\n\nHermes est un moteur JavaScript optimisé pour React Native. Il réduit le temps de démarrage, la consommation mémoire et la taille du bundle.\n\n## 2. FlashList\n\nFlashList remplace FlatList pour les grandes listes. Il utilise le recyclage des vues et le calcul asynchrone de layout pour des performances optimales.\n\n## 3. Optimisation des images\n\nUtilisez des images aux bonnes dimensions, le format WebP, le lazy loading, et un cache disque avec react-native-fast-image.\n\n## 4. Profilage avec le Metro bundler\n\nUtilisez le profileur du Metro bundler et React DevTools pour identifier les goulots d'étranglement.\n\n## Résumé\n\n- Hermes : moteur JS optimisé\n- FlashList : listes hautes performances\n- Images optimisées (WebP, cache, lazy loading)\n- Profilage avec Metro et React DevTools"
  },
  {
    "title": "Hors ligne et Stockage Local",
    "durationMin": 75,
    "contentMarkdown": "# Hors ligne et Stockage Local\n\n## Introduction\n\nUne application mobile de qualité doit fonctionner même sans connexion réseau. La gestion du mode hors ligne implique de détecter la connectivité, stocker les données localement et synchroniser quand le réseau revient.\n\n## 1. Détection de connectivité avec NetInfo\n\nNetInfo permet de détecter l'état de la connexion réseau (WiFi, cellulaire, aucun) et d'écouter les changements en temps réel.\n\n## 2. WatermelonDB\n\nWatermelonDB est une base de données performante pour React Native. Elle utilise SQLite sous le capot et supporte la synchronisation lazy avec un serveur.\n\n## 3. AsyncStorage avancé\n\nAsyncStorage est idéal pour les petites données (tokens, préférences). Pour les données complexes, utilisez WatermelonDB ou SQLite.\n\n## 4. Stratégies de synchronisation\n\nSynchronisation en arrière-plan, conflits de données (last-write-wins, merge), files d'attente d'opérations hors ligne.\n\n## Résumé\n\n- NetInfo : détection de connectivité\n- WatermelonDB : base de données locale avec sync lazy\n- AsyncStorage : données simples et préférences\n- Stratégies de sync : files d'attente, résolution de conflits"
  },
  {
    "title": "Déploiement et CI/CD",
    "durationMin": 70,
    "contentMarkdown": "# Déploiement et CI/CD\n\n## Introduction\n\nLe déploiement d'une application React Native implique des outils spécifiques : EAS Build pour la compilation cloud, TestFlight et Play Store pour la distribution, et CodePush pour les mises à jour OTA.\n\n## 1. EAS Build\n\nEAS Build compile votre app dans le cloud sans configuration locale complexe. Supporte les builds iOS et Android avec des profils de configuration.\n\n## 2. TestFlight et Play Store\n\nDistribuez des versions bêta via TestFlight (iOS) et le Play Console (Android). Gérez les certificats et les profils de provisionnement.\n\n## 3. CodePush avec EAS Update\n\nLes mises à jour OTA permettent de déployer des modifications JavaScript et assets sans passer par l'App Store.\n\n## 4. GitHub Actions CI/CD\n\nAutomatisez les tests, la compilation et le déploiement avec GitHub Actions. Exécutez les tests unitaires avant chaque build.\n\n## Résumé\n\n- EAS Build : compilation cloud\n- TestFlight/Play Store : distribution bêta\n- CodePush/EAS Update : mises à jour OTA\n- GitHub Actions : CI/CD automatisé"
  }
],
  project: {
  "title": "Application de Gestion de Tâches Hors Ligne",
  "instructions": "# Application de Gestion de Tâches Hors Ligne — Offline Todo App\n\n## Objectif\n\nCréer une application React Native avancée qui gère des listes de tâches avec synchronisation complète hors ligne, animations fluides et déploiement CI/CD.\n\n## Consignes\n\n### 1. Fonctionnalités obligatoires\n\n- **CRUD complet** : créer, lire, modifier et supprimer des tâches\n- **Catégories** : chaque tâche appartient à une catégorie (personnel, travail, courses)\n- **Priorité** : faible, moyenne, haute — avec code couleur\n- **Recherche** : filtrer les tâches par titre ou catégorie\n- **Mode hors ligne** : toutes les opérations fonctionnent sans réseau\n- **Synchronisation** : quand le réseau revient, les modifications sont envoyées au serveur\n\n### 2. Composants obligatoires\n\n- **TaskCard** : carte de tâche animée avec geste de glissement pour supprimer\n- **CategoryFilter** : barre de filtres horizontale animée\n- **AddTaskModal** : modal de création avec formulaire et validation\n- **OfflineBanner** : bannière animée indiquant le mode hors ligne\n- **SyncIndicator** : indicateur de synchronisation en cours\n\n### 3. Technologies requises\n\n- **React Native Reanimated 3** pour toutes les animations\n- **Gesture Handler** pour les gestes de glissement\n- **AsyncStorage** avec système de cache horodaté pour le stockage local\n- **NetInfo** pour la détection de connectivité\n- **FlashList** pour la liste performante des tâches\n- **React Navigation** avec Stack et Tab navigators\n\n### 4. Architecture\n\n- **Dossier `src/`** : components, screens, services, hooks, utils\n- **Service `taskService.ts`** : logique CRUD avec fallback local\n- **Service `syncService.ts`** : file d'attente et synchronisation\n- **Hook `useNetInfo`** : wrapper personnalisé pour NetInfo\n- **Context `TaskContext`** : état global des tâches\n\n### 5. Fonctionnalités bonus (optionnelles)\n\n- Animations de réordonnancement des tâches (drag-and-drop)\n- Notifications locales pour les échéances\n- Statistiques par catégorie (diagramme avec react-native-chart-kit)\n- Thème sombre / clair avec persistance\n\n## Contraintes techniques\n\n- **Expo SDK 51+** avec TypeScript\n- **Reanimated 3** pour les animations (pas l'API Animated)\n- **FlashList** pour la liste (pas FlatList)\n- **Aucune donnée en dur** : tout est géré dynamiquement\n- Minimum 5 animations distinctes (entrée, sortie, layout, geste, transition)\n\n## Critères d'évaluation\n\n- **Fonctionnalités** : CRUD complet, catégories, priorité, recherche, mode hors ligne\n- **Animations** : fluidité, gestes de glissement, transitions, animations de layout\n- **Mode hors ligne** : détection réseau, stockage local, file d'attente, synchronisation\n- **Architecture** : séparation des responsabilités, hooks personnalisés, services isolés\n- **Performance** : FlashList, memoisation, images optimisées, pas de re-rendus inutiles",
  "evaluationCriteria": [
    "Fonctionnalités : CRUD complet, catégories, priorité, recherche et mode hors ligne fonctionnels",
    "Animations : minimum 5 animations fluides (entrées/sorties, gestes, layout, transitions d'écran)",
    "Mode hors ligne : détection réseau, stockage persistant, file d'attente de synchronisation",
    "Architecture : séparation composants/services/hooks, code TypeScript propre et typé",
    "Performance : FlashList, memoisation correcte, pas de re-rendus inutiles, images optimisées"
  ]
},
};
