declare module 'lucide-react-native' {
  import { ComponentType } from 'react';
  import { SvgProps } from 'react-native-svg';

  export interface IconProps extends SvgProps {
    color?: string;
    size?: number;
    strokeWidth?: number;
    absoluteStrokeWidth?: boolean;
  }

  export type Icon = ComponentType<IconProps>;
  export type LucideIcon = Icon;

  export const Activity: Icon;
  export const AlertCircle: Icon;
  export const AlertTriangle: Icon;
  export const ArrowDown: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const ArrowUp: Icon;
  export const Award: Icon;
  export const BarChart2: Icon;
  export const BarChart3: Icon;
  export const Bell: Icon;
  export const Bookmark: Icon;
  export const BookmarkCheck: Icon;
  export const BookOpen: Icon;
  export const Brain: Icon;
  export const Calendar: Icon;
  export const Camera: Icon;
  export const Check: Icon;
  export const CheckCheck: Icon;
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const ChevronDown: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronUp: Icon;
  export const Circle: Icon;
  export const Clock: Icon;
  export const Cloud: Icon;
  export const Code2: Icon;
  export const Container: Icon;
  export const CreditCard: Icon;
  export const Crown: Icon;
  export const Database: Icon;
  export const Download: Icon;
  export const ExternalLink: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const FileJson: Icon;
  export const FileText: Icon;
  export const FileUp: Icon;
  export const Fingerprint: Icon;
  export const Flame: Icon;
  export const FolderCode: Icon;
  export const FolderKanban: Icon;
  export const FolderOpen: Icon;
  export const GitBranch: Icon;
  export const Globe: Icon;
  export const GraduationCap: Icon;
  export const HardDrive: Icon;
  export const Heart: Icon;
  export const HelpCircle: Icon;
  export const Home: Icon;
  export const House: Icon;
  export const Info: Icon;
  export const Layout: Icon;
  export const ListChecks: Icon;
  export const Lock: Icon;
  export const LogOut: Icon;
  export const Mail: Icon;
  export const MailCheck: Icon;
  export const Maximize2: Icon;
  export const MessageCircle: Icon;
  export const MessageSquare: Icon;
  export const Moon: Icon;
  export const Palette: Icon;
  export const Pause: Icon;
  export const PenTool: Icon;
  export const Percent: Icon;
  export const Play: Icon;
  export const PlayCircle: Icon;
  export const Plus: Icon;
  export const PlusCircle: Icon;
  export const RefreshCw: Icon;
  export const RotateCcw: Icon;
  export const Search: Icon;
  export const Send: Icon;
  export const Server: Icon;
  export const Share2: Icon;
  export const Shield: Icon;
  export const Sparkles: Icon;
  export const ShieldCheck: Icon;
  export const Smartphone: Icon;
  export const Star: Icon;
  export const StickyNote: Icon;
  export const Sun: Icon;
  export const Target: Icon;
  export const Terminal: Icon;
  export const Trash2: Icon;
  export const TrendingUp: Icon;
  export const Trophy: Icon;
  export const User: Icon;
  export const Users: Icon;
  export const Video: Icon;
  export const WifiOff: Icon;
  export const X: Icon;
  export const XCircle: Icon;
  export const Zap: Icon;
}
