const project = {
  "title": "Application de Gestion de Tâches Hors Ligne",
  "instructions": "# Application de Gestion de Tâches Hors Ligne — Offline Todo App\n\n## Objectif\n\nCréer une application React Native avancée qui gère des listes de tâches avec synchronisation complète hors ligne, animations fluides et déploiement CI/CD.\n\n## Consignes\n\n### 1. Fonctionnalités obligatoires\n\n- **CRUD complet** : créer, lire, modifier et supprimer des tâches\n- **Catégories** : chaque tâche appartient à une catégorie (personnel, travail, courses)\n- **Priorité** : faible, moyenne, haute — avec code couleur\n- **Recherche** : filtrer les tâches par titre ou catégorie\n- **Mode hors ligne** : toutes les opérations fonctionnent sans réseau\n- **Synchronisation** : quand le réseau revient, les modifications sont envoyées au serveur\n\n### 2. Composants obligatoires\n\n- **TaskCard** : carte de tâche animée avec geste de glissement pour supprimer\n- **CategoryFilter** : barre de filtres horizontale animée\n- **AddTaskModal** : modal de création avec formulaire et validation\n- **OfflineBanner** : bannière animée indiquant le mode hors ligne\n- **SyncIndicator** : indicateur de synchronisation en cours\n\n### 3. Technologies requises\n\n- **React Native Reanimated 3** pour toutes les animations\n- **Gesture Handler** pour les gestes de glissement\n- **AsyncStorage** avec système de cache horodaté pour le stockage local\n- **NetInfo** pour la détection de connectivité\n- **FlashList** pour la liste performante des tâches\n- **React Navigation** avec Stack et Tab navigators\n\n### 4. Architecture\n\n- **Dossier `src/`** : components, screens, services, hooks, utils\n- **Service `taskService.ts`** : logique CRUD avec fallback local\n- **Service `syncService.ts`** : file d'attente et synchronisation\n- **Hook `useNetInfo`** : wrapper personnalisé pour NetInfo\n- **Context `TaskContext`** : état global des tâches\n\n### 5. Fonctionnalités bonus (optionnelles)\n\n- Animations de réordonnancement des tâches (drag-and-drop)\n- Notifications locales pour les échéances\n- Statistiques par catégorie (diagramme avec react-native-chart-kit)\n- Thème sombre / clair avec persistance\n\n## Contraintes techniques\n\n- **Expo SDK 51+** avec TypeScript\n- **Reanimated 3** pour les animations (pas l'API Animated)\n- **FlashList** pour la liste (pas FlatList)\n- **Aucune donnée en dur** : tout est géré dynamiquement\n- Minimum 5 animations distinctes (entrée, sortie, layout, geste, transition)\n\n## Critères d'évaluation\n\n- **Fonctionnalités** : CRUD complet, catégories, priorité, recherche, mode hors ligne\n- **Animations** : fluidité, gestes de glissement, transitions, animations de layout\n- **Mode hors ligne** : détection réseau, stockage local, file d'attente, synchronisation\n- **Architecture** : séparation des responsabilités, hooks personnalisés, services isolés\n- **Performance** : FlashList, memoisation, images optimisées, pas de re-rendus inutiles",
  "evaluationCriteria": [
    "Fonctionnalités : CRUD complet, catégories, priorité, recherche et mode hors ligne fonctionnels",
    "Animations : minimum 5 animations fluides (entrées/sorties, gestes, layout, transitions d'écran)",
    "Mode hors ligne : détection réseau, stockage persistant, file d'attente de synchronisation",
    "Architecture : séparation composants/services/hooks, code TypeScript propre et typé",
    "Performance : FlashList, memoisation correcte, pas de re-rendus inutiles, images optimisées"
  ]
};

export default project;
