const project = {
  "title": "Tableau Kanban",
  "instructions": "# Tableau Kanban — Kanban Board\n\n## Objectif\n\nCréer une application React de tableau Kanban permettant de gérer des tâches avec drag-and-drop entre colonnes.\n\n---\n\n## Consignes\n\n### 1. Structure de base\n\n- Trois colonnes par défaut : **À faire**, **En cours**, **Terminé**\n- Chaque tâche contient : titre, description (optionnelle), date de création, couleur de priorité (rouge/verte/bleue)\n- Possibilité d'ajouter, modifier et supprimer des tâches\n\n### 2. Drag and Drop\n\n- Utiliser `@dnd-kit/core` ou `react-beautiful-dnd` pour le glisser-déposer\n- Permettre le déplacement d'une tâche entre colonnes\n- Permettre le réordonnancement des tâches au sein d'une même colonne\n- Afficher un feedback visuel pendant le drag (ombre, opacité, placeholder)\n\n### 3. Filtrage et recherche\n\n- Barre de recherche filtrant les tâches par titre\n- Filtres par couleur de priorité (toutes, rouge, verte, bleue)\n- Les filtres s'appliquent en temps réel sans recharger les données\n\n### 4. Dark mode\n\n- Bascule clair/sombre via Context API\n- Le thème est persisté dans localStorage\n- Appliquer des variables CSS pour la cohérence visuelle\n\n### 5. Persistance localStorage\n\n- Sauvegarder automatiquement les colonnes et tâches dans localStorage\n- Charger les données au démarrage de l'application\n- Ne jamais perdre les données en cas de rechargement de page\n\n---\n\n## Contraintes techniques\n\n- **React + TypeScript** obligatoire\n- **Vite** comme outil de build\n- Composants fonctionnels uniquement\n- Hooks personnalisés pour la logique métier\n- Code bien structuré (dossier `components/`, `hooks/`, `context/`, `types/`)\n\n---\n\n## Critères d'évaluation (5 critères)\n\n1. **Drag & Drop** : le glisser-déposer fonctionne entre colonnes et au sein d'une colonne, avec feedback visuel approprié\n2. **CRUD complet** : ajout, modification et suppression de tâches fonctionnent correctement avec validation\n3. **Architecture et hooks** : découpage en composants propres, hooks personnalisés réutilisables, contexte pour le thème\n4. **Fonctionnalités transversales** : filtrage, recherche, dark mode et persistence localStorage tous fonctionnels\n5. **Qualité du code** : typage TypeScript strict, code lisible, bonnes pratiques React, absence de tout/rebuts inutiles",
  "evaluationCriteria": [
    "Drag & Drop fonctionnel : déplacement entre colonnes et réordonnancement avec feedback visuel",
    "CRUD complet : ajout, modification et suppression de tâches avec validation",
    "Architecture et hooks : composants propres, hooks personnalisés, contexte pour le thème",
    "Fonctionnalités transversales : filtrage, recherche, dark mode, persistence localStorage",
    "Qualité du code : TypeScript strict, lisibilité, bonnes pratiques React"
  ]
};

export default project;
