const project = {
  "title": "Analyse Exploratoire de Donnees E-commerce",
  "instructions": "# Analyse Exploratoire de Donnees E-commerce\n\n## Objectif\n\nRealiser une analyse exploratoire complete (EDA) sur un jeu de donnees de commandes e-commerce en utilisant Pandas, NumPy, Matplotlib et Seaborn. Le notebook doit etre structure, commente et visuellement clair.\n\n---\n\n## Donnees\n\nLe jeu de donnees contient les colonnes suivantes :\n\n| Colonne | Type | Description |\n|---------|------|-------------|\n| order_id | str | Identifiant unique de la commande |\n| customer_id | str | Identifiant client |\n| customer_segment | str | Premium, Regular, Nouveau |\n| product_category | str | Electronique, Vetement, Maison, Sport, Livres |\n| order_amount | float | Montant de la commande |\n| quantity | int | Nombre d'articles |\n| discount_percent | float | Pourcentage de remise |\n| order_date | datetime | Date de la commande |\n| region | str | Ile-de-France, Auvergne-Rhone-Alpes, etc. |\n\n---\n\n## Taches d'Analyse\n\n### 1. Chargement et Nettoyage (Pandas)\n\n- Charger le CSV avec Pandas\n- Afficher les 5 premieres lignes et les infos generales (.info(), .describe())\n- Detecter et gerer les valeurs manquantes\n- Convertir les types si necessaire (dates, categories)\n- Creer de nouvelles colonnes : mois, trimestre, chiffre d'affaires net (apres remise)\n\n### 2. Analyse Univariee\n\n- Distribution du montant des commandes (histogramme + KDE)\n- Nombre de commandes par categorie de produit (barplot)\n- Repartition des segments clients (pie chart)\n- Boxplot du montant par region\n\n### 3. Analyse Bivariee\n\n- Montant moyen par categorie et segment (groupby + barplot)\n- Matrice de correlation entre montant, quantite et remise (heatmap)\n- Evolution du chiffre d'affaires mensuel (line plot)\n- Comparaison des regions (boxplot ou violinplot)\n\n### 4. Analyse Multivariee\n\n- Pairplot colore par segment client\n- Heatmap de correlation des variables numeriques\n- FacetGrid : distribution du montant par region et categorie\n\n### 5. Insights et Conclusions\n\n- Identifier les 3 categories les plus rentables\n- Identifier les pics de ventes (periodes)\n- Formuler 3 recommandements metier basees sur les donnees\n\n---\n\n## Livrables\n\n- Un fichier notebook Jupyter (.ipynb) avec toutes les cellules\n- Les graphiques sont sauvegardes en PNG haute resolution\n- Les commentaires Markdown expliquent chaque etape\n- Un resume final avec les insights cles\n\n---\n\n## Contraintes Techniques\n\n- Python 3.10+ avec Pandas, NumPy, Matplotlib, Seaborn\n- Tous les graphiques doivent etre personnalises (titres, labels, legends)\n- Utiliser sns.set_style() et sns.set_palette() pour l'esthetique\n- Les labels des graphiques sont en francais\n- Le notebook doit etre reproductible (seed pour la reproductibilite)",
  "evaluationCriteria": [
    "Nettoyage des donnees (gestion des NaN, conversion des types, nouvelles colonnes)",
    "Analyse (toutes les visualisations demandees sont presentes et correctes)",
    "Qualite des graphiques (titres, labels, legends, personnalisation esthetique)",
    "Insights (conclusions pertinentes basees sur les donnees, recommandations metier)",
    "Structure du notebook (organisation claire, commentaires Markdown, code propre)"
  ]
};

export default project;
