import { Level } from '@prisma/client';

export const dockerProduction = {
  techSlug: "docker",
  title: "Docker en Production",
  description: "Orchestration avec Swarm, monitoring, securite et CI/CD pour Docker en environnement de production.",
  level: Level.advanced,
  durationMin: 240,
  lessons: [
    {
      "title": "Docker Swarm et Orchestration",
      "durationMin": 60,
      "contentMarkdown": "# Docker Swarm et Orchestration\n\n## Introduction\n\nDocker Swarm transforme un ensemble de machines en un cluster Docker unique. Il gere le deploiement, la mise a l'echelle et la haute disponibilite des services.\n\n---\n\n## 1. Initialisation du Swarm\n\n```bash\n# Initialiser le manager\ndocker swarm init --advertise-addr 192.168.1.100\n\n# Obtenir la commande pour les workers\ndocker swarm join-token worker\n\n# Lister les noeuds\ndocker node ls\n```\n\n---\n\n## 2. Services et Tasks\n\n```bash\n# Creer un service\ndocker service create --name web --replicas 3 -p 80:80 nginx\n\n# Lister les services\ndocker service ls\n\n# Voir les tasks (conteneurs) d'un service\ndocker service ps web\n\n# Mettre a l'echelle\ndocker service scale web=5\n\n# Supprimer un service\ndocker service rm web\n```\n\n---\n\n## 3. Overlay Networks\n\n```bash\n# Creer un reseau overlay\ndocker network create --driver overlay mon-reseau\n\n# Utiliser le reseau dans un service\ndocker service create --name api --network mon-reseau --replicas 2 mon-api\n\n# Les services peuvent communiquer par nom\n# api:3000 est accessible depuis tout le swarm\n```\n\n---\n\n## 4. Mise a Jour Rolling\n\n```bash\n# Mise a jour avec controle\ndocker service update \\\n  --image mon-api:2.0.0 \\\n  --update-parallelism 2 \\\n  --update-delay 10s \\\n  --update-failure-action rollback \\\n  api\n\n# Rollback automatique\ndocker service rollback api\n\n# Inspecter l'etat\ndocker service inspect --pretty api\n```",
    },
    {
      "title": "Monitoring et Logging",
      "durationMin": 60,
      "contentMarkdown": "# Monitoring et Logging\n\n## Introduction\n\nEn production, il est essentiel de surveiller l'etat de vos conteneurs et de centraliser les logs. Docker fournit des outils integres qui se combinent avec des solutions externes comme Prometheus et ELK.\n\n---\n\n## 1. Docker Events et Stats\n\n```bash\n# Surveiller les evenements en temps reel\ndocker events\n\n# Filtrer les evenements\ndocker events --filter 'type=container' --filter 'event=die'\n\n# Statistiques des conteneurs\ndocker stats\n\n# Statistiques d'un conteneur specifique\ndocker stats mon-conteneur --no-stream\n\n# Historique des evenements\ndocker events --since '2024-01-01' --until '2024-01-02'\n```\n\n---\n\n## 2. Logging avec Docker\n\n```bash\n# Voir les logs d'un conteneur\ndocker logs mon-conteneur\n\n# Suivre les logs en temps reel\ndocker logs -f mon-conteneur\n\n# Logs avec timestamp\ndocker logs --timestamps mon-conteneur\n\n# Dernieres N lignes\ndocker logs --tail 100 mon-conteneur\n\n# Driver de logging JSON (par defaut)\ndocker run --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 nginx\n```\n\n---\n\n## 3. Prometheus et Grafana\n\n```yaml\n# docker-compose.monitoring.yml\nversion: '3.8'\nservices:\n  prometheus:\n    image: prom/prometheus\n    volumes:\n      - ./prometheus.yml:/etc/prometheus/prometheus.yml\n    ports:\n      - \"9090:9090\"\n\n  grafana:\n    image: grafana/grafana\n    ports:\n      - \"3000:3000\"\n    environment:\n      - GF_SECURITY_ADMIN_PASSWORD=admin\n    volumes:\n      - grafana-data:/var/lib/grafana\n\n  node-exporter:\n    image: prom/node-exporter\n    ports:\n      - \"9100:9100\"\n\nvolumes:\n  grafana-data:\n```\n\n---\n\n## 4. ELK Stack pour Logs Centralises\n\n```yaml\n# docker-compose.elk.yml\nversion: '3.8'\nservices:\n  elasticsearch:\n    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0\n    environment:\n      - discovery.type=single-node\n    ports:\n      - \"9200:9200\"\n\n  logstash:\n    image: docker.elastic.co/logstash/logstash:8.10.0\n    volumes:\n      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf\n    ports:\n      - \"5000:5000\"\n\n  kibana:\n    image: docker.elastic.co/kibana/kibana:8.10.0\n    ports:\n      - \"5601:5601\"\n    environment:\n      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200\n```",
    },
    {
      "title": "Securite des Conteneurs",
      "durationMin": 60,
      "contentMarkdown": "# Securite des Conteneurs\n\n## Introduction\n\nLa securite est une preoccupation majeure en production. Docker propose plusieurs mecanismes pour isoler et proteger vos conteneurs.\n\n---\n\n## 1. Principes de Securite\n\n```bash\n# Ne pas tourner en root\ndocker run --user 1000:1000 nginx\n\n# Filesystem en lecture seule\ndocker run --read-only --tmpfs /tmp nginx\n\n# Capacites reduites\ndocker run --cap-drop ALL --cap-add NET_BIND_SERVICE nginx\n\n# Securite du kernel\ndocker run --security-opt no-new-privileges:true nginx\n```\n\n---\n\n## 2. Gestion des Secrets\n\n```bash\n# Creer un secret (Swarm)\necho \"mon-mot-de-passe\" | docker secret create db_password -\n\n# Lister les secrets\ndocker secret ls\n\n# Utiliser un secret dans un service\ndocker service create \\\n  --name api \\\n  --secret db_password \\\n  --secret api_key \\\n  mon-api\n\n# Les secrets sont montes dans /run/secrets/\n```\n\n---\n\n## 3. Scan d'Images\n\n```bash\n# Scanner une image avec Docker Scout\ndocker scout quickview mon-image:latest\n\n# Audit detaille\ndocker scout cves mon-image:latest\n\n# Comparer deux versions\ndocker scout compare mon-image:v1 mon-image:v2\n\n# Recommandations\ndocker scout recommendations mon-image:latest\n```\n\n---\n\n## 4. Reseaux Securises\n\n```bash\n# Isoler les services\ndocker network create --internal backend\ndocker network create frontend\n\n# Service backend sans acces externe\ndocker service create --name db --network backend postgres:16\n\n# Service frontend avec acces\ndocker service create --name api \\\n  --network backend \\\n  --network frontend \\\n  -p 80:80 \\\n  mon-api\n\n# Utiliser des proxies TLS\ndocker service create --name proxy \\\n  -p 443:443 \\\n  --network frontend \\\n  --secret ssl_cert \\\n  traefik:v3.0\n```",
    },
    {
      "title": "CI/CD et Deploiement Continue",
      "durationMin": 60,
      "contentMarkdown": "# CI/CD et Deploiement Continue\n\n## Introduction\n\nL'automatisation du build, du test et du deploiement est essentielle pour livrer des applications Docker en production de maniere fiable.\n\n---\n\n## 1. Dockerfile Optimise\n\n```dockerfile\n# Multi-stage build\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nEXPOSE 3000\nUSER node\nCMD [\"node\", \"dist/index.js\"]\n```\n\n---\n\n## 2. CI avec GitHub Actions\n\n```yaml\nname: Docker CI\non:\n  push:\n    branches: [main]\n\njobs:\n  build-and-push:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n\n      - name: Login to Docker Hub\n        uses: docker/login-action@v3\n        with:\n          username: ${{ secrets.DOCKER_USERNAME }}\n          password: ${{ secrets.DOCKER_PASSWORD }}\n\n      - name: Build and push\n        uses: docker/build-push-action@v5\n        with:\n          push: true\n          tags: user/app:${{ github.sha }}\n```\n\n---\n\n## 3. Deploiement avec Portainer\n\n```bash\n# Installer Portainer\ndocker volume create portainer_data\ndocker run -d \\\n  -p 9000:9000 \\\n  -v /var/run/docker.sock:/var/run/docker.sock \\\n  -v portainer_data:/data \\\n  portainer/portainer-ce:2.21.0\n\n# Stack via API\ncurl -X POST http://localhost:9000/api/stacks \\\n  -H \"Authorization: Bearer TOKEN\" \\\n  -d '{\n    \"name\": \"production\",\n    \"fileContent\": \"version: \"3.8\"\\nservices:\\n  web:\\n    image: nginx\"\n  }'\n```\n\n---\n\n## 4. Blue-Green Deploiement\n\n```bash\n# Deploiement blue (actuel)\ndocker service create --name app-blue --replicas 3 -p 8080:80 mon-app:1.0\n\n# Deploiement green (nouveau)\ndocker service create --name app-green --replicas 3 mon-app:2.0\n\n# Bascule du trafic\ndocker service update --publish-rm 8080:80 app-blue\ndocker service update --publish-add 8080:80 app-green\n\n# Nettoyage apres validation\ndocker service rm app-blue\n```",
    },
  ],
};