import { Level } from '@prisma/client';

export const pythonBackend = {
  techSlug: "python",
  title: "Python pour le Backend",
  description: "Decouvrez comment creer des API modernes et performantes avec Python, FastAPI, SQLAlchemy et PostgreSQL. Du premier endpoint au deploiement en production.",
  level: Level.beginner,
  durationMin: 180,
  lessons: [
    {
      "title": "Introduction a Python et FastAPI",
      "durationMin": 45,
      "contentMarkdown": "# Introduction a Python et FastAPI\n\n## Introduction\n\nFastAPI est un framework web moderne pour Python, construit au-dessus de Starlette et Pydantic. Il est concu pour etre rapide, facile a utiliser et offrir une documentation automatique. Ce module couvre le typage, l'asynchronisme et la creation de votre premier endpoint.\n\n---\n\n## 1. Environnement Python et Typage\n\nPython 3.10+ supporte le typage statique grace aux annotations de type. FastAPI en tire parti pour la validation automatique.\n\n```python\n# Typage de base en Python\ndef calculer_prix_ht(prix_ttc: float, taux_tva: float = 0.20) -> float:\n    \"\"\"Calcule le prix hors taxes a partir du prix TTC.\"\"\"\n    return round(prix_ttc / (1 + taux_tva), 2)\n\n# Types complexes avec dataclasses\nfrom dataclasses import dataclass\nfrom typing import Optional\n\n@dataclass\nclass Utilisateur:\n    id: int\n    nom: str\n    email: str\n    age: Optional[int] = None\n```\n\n**Types utiles pour FastAPI :**\n- `str, int, float, bool` : types primitifs\n- `Optional[str]` : valeur pouvant etre None\n- `list[str]` : liste de chaines\n- `dict[str, Any]` : dictionnaire a cles string\n\n---\n\n## 2. Premier endpoint avec FastAPI\n\n```python\nfrom fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI(title=\"Mon API\", version=\"1.0.0\")\n\n@app.get(\"/\")\ndef accueil():\n    return {\"message\": \"Bienvenue sur mon API\"}\n\n@app.post(\"/items\")\nasync def creer_item(item: ItemCreate):\n    total = item.price + item.tax\n    return {\"id\": 1, \"name\": item.name, \"price\": item.price, \"total\": total}\n```\n\n---\n\n## 3. Async/Await en Python\n\nFastAPI supporte nativement l'asynchronisme. Les routes async permettent de gerer plusieurs requetes simultanement sans bloquer.\n\n```python\nimport httpx\nimport asyncio\nfrom fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/async\")\nasync def route_asynchrone():\n    async with httpx.AsyncClient() as client:\n        response = await client.get(\"https://jsonplaceholder.typicode.com/todos/1\")\n        return response.json()\n```\n\n---\n\n## 4. Validation avec Pydantic\n\nPydantic valide automatiquement les donnees. Il genere des erreurs claires si les donnees ne sont pas conformes.\n\n```python\nfrom pydantic import BaseModel, Field\nfrom datetime import datetime\n\nclass UserCreate(BaseModel):\n    name: str = Field(..., min_length=2, max_length=50)\n    email: str = Field(..., pattern=r\"^[\\\\w.-]+@[\\\\w.-]+\\\\.\\\\w+$\")\n    age: int = Field(..., ge=13, le=120)\n```",
    },
    {
      "title": "CRUD avec SQLAlchemy et PostgreSQL",
      "durationMin": 45,
      "contentMarkdown": "# CRUD avec SQLAlchemy et PostgreSQL\n\n## Introduction\n\nSQLAlchemy est l'ORM le plus populaire de Python. Couple a une base PostgreSQL, il permet de manipuler des donnees relationnelles de maniere elegante et typee.\n\n---\n\n## 1. Configuration et Modeles\n\n```python\nfrom sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker\nfrom sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column\nfrom sqlalchemy import String, Float\n\nDATABASE_URL = \"postgresql+asyncpg://user:password@localhost:5432/mydb\"\nengine = create_async_engine(DATABASE_URL, echo=True)\nasync_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)\n\nclass Base(DeclarativeBase):\n    pass\n\nclass Product(Base):\n    __tablename__ = \"products\"\n    id: Mapped[int] = mapped_column(primary_key=True)\n    name: Mapped[str] = mapped_column(String(100))\n    price: Mapped[float] = mapped_column(Float)\n    stock: Mapped[int] = mapped_column(default=0)\n```\n\n---\n\n## 2. CRUD Asynchrone\n\n```python\nfrom sqlalchemy import select\nfrom database import Product, async_session\n\nasync def creer_produit(name: str, price: float) -> Product:\n    async with async_session() as session:\n        produit = Product(name=name, price=price)\n        session.add(produit)\n        await session.commit()\n        await session.refresh(produit)\n        return produit\n\nasync def lister_produits() -> list[Product]:\n    async with async_session() as session:\n        result = await session.execute(select(Product))\n        return list(result.scalars().all())\n```\n\n---\n\n## 3. Migrations avec Alembic\n\n```bash\npip install alembic\nalembic init alembic\nalembic revision --autogenerate -m \"add products table\"\nalembic upgrade head\n```\n\n---\n\n## 4. Routes CRUD avec FastAPI\n\n```python\nfrom fastapi import FastAPI, HTTPException, Query\nfrom pydantic import BaseModel\nfrom typing import Optional\n\n@app.get(\"/products\", response_model=list[ProductResponse])\nasync def list_products(skip: int = Query(0, ge=0), limit: int = Query(10, ge=1, le=100)):\n    return await crud.lister_produits(skip=skip, limit=limit)\n\n@app.get(\"/products/{product_id}\", response_model=ProductResponse)\nasync def get_product(product_id: int):\n    produit = await crud.obtenir_produit(product_id)\n    if not produit:\n        raise HTTPException(status_code=404, detail=\"Produit non trouve\")\n    return produit\n```",
    },
    {
      "title": "Authentification et Securite",
      "durationMin": 45,
      "contentMarkdown": "# Authentification et Securite\n\n## Introduction\n\nLa securite d'une API est essentielle. Ce module couvre l'authentification JWT, OAuth2 avec FastAPI et le hashage des mots de passe.\n\n---\n\n## 1. JWT avec FastAPI\n\n```python\nfrom datetime import datetime, timedelta\nfrom fastapi import Depends, HTTPException, status\nfrom fastapi.security import OAuth2PasswordBearer\nfrom jose import JWTError, jwt\nfrom passlib.context import CryptContext\n\nSECRET_KEY = \"votre-cle-secrete\"\nALGORITHM = \"HS256\"\nACCESS_TOKEN_EXPIRE_MINUTES = 30\n\npwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\noauth2_scheme = OAuth2PasswordBearer(tokenUrl=\"/auth/login\")\n\ndef creer_access_token(data: dict, expires_delta: timedelta | None = None) -> str:\n    to_encode = data.copy()\n    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))\n    to_encode.update({\"exp\": expire})\n    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)\n```\n\n---\n\n## 2. Middleware d'Authentification\n\n```python\nasync def get_current_user(token: str = Depends(oauth2_scheme)):\n    return verifier_token(token)\n\n@app.get(\"/protected\")\nasync def route_protegee(current_user = Depends(get_current_user)):\n    return {\"message\": f\"Bienvenue {current_user.email}\"}\n```\n\n---\n\n## 3. Inscription et Connexion\n\n```python\n@app.post(\"/auth/register\")\nasync def register(user_data: UserCreate):\n    hashed = pwd_context.hash(user_data.password)\n    user = User(email=user_data.email, password=hashed, name=user_data.name)\n    session.add(user)\n    await session.commit()\n    return user\n\n@app.post(\"/auth/login\")\nasync def login(email: str, password: str):\n    user = await get_user_by_email(email)\n    if not user or not pwd_context.verify(password, user.password):\n        raise HTTPException(status_code=401, detail=\"Email ou mot de passe incorrect\")\n    token = creer_access_token(data={\"sub\": str(user.id), \"email\": user.email})\n    return {\"access_token\": token, \"token_type\": \"bearer\"}\n```\n\n---\n\n## 4. Configuration CORS\n\n```python\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=[\"http://localhost:3000\", \"https://mon-app.com\"],\n    allow_credentials=True,\n    allow_methods=[\"GET\", \"POST\", \"PUT\", \"DELETE\"],\n    allow_headers=[\"*\"],\n)\n```",
    },
    {
      "title": "Tests et Deploiement",
      "durationMin": 45,
      "contentMarkdown": "# Tests et Deploiement\n\n## Introduction\n\nEcrire des tests et automatiser le deploiement sont des etapes indispensables pour une API de qualite production.\n\n---\n\n## 1. Tests avec pytest et TestClient\n\n```python\nfrom fastapi.testclient import TestClient\nfrom main import app\n\nclient = TestClient(app)\n\ndef test_creer_produit():\n    response = client.post(\"/products\", json={\"name\": \"Clavier\", \"price\": 89.99, \"stock\": 10})\n    assert response.status_code == 201\n    assert response.json()[\"name\"] == \"Clavier\"\n\ndef test_lister_produits():\n    response = client.get(\"/products\")\n    assert response.status_code == 200\n    assert isinstance(response.json(), list)\n```\n\n---\n\n## 2. Tests Asynchrones\n\n```python\nimport pytest\nfrom httpx import AsyncClient, ASGITransport\nfrom main import app\n\n@pytest.mark.anyio\nasync def test_creer_produit_async():\n    transport = ASGITransport(app=app)\n    async with AsyncClient(transport=transport, base_url=\"http://test\") as ac:\n        response = await ac.post(\"/products\", json={\"name\": \"Souris\", \"price\": 49.99})\n        assert response.status_code == 201\n```\n\n---\n\n## 3. Dockerfile et Deploiement\n\n```dockerfile\nFROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n```\n\n---\n\n## 4. Structure du Projet\n\n```\napp/\n  main.py\n  database.py\n  models/\n  routes/\n  tests/\nDockerfile\nrequirements.txt\n```",
    },
  ],
};