const project = {
  "title": "Application de Gestion de Notes",
  "instructions": "# Application de Gestion de Notes — Notes App\n\n## Objectif\n\nCréer une application Flutter pour gérer des notes personnelles avec des catégories, un système de recherche et un design Material 3 soigné.\n\n## Consignes\n\n### 1. Fonctionnalités obligatoires\n\n- **CRUD des notes** : créer, modifier, supprimer des notes (titre + contenu)\n- **Catégories** : chaque note a une catégorie (travail, personnel, idées, courses)\n- **Recherche** : filtrer les notes par titre ou contenu\n- **Tri** : par date de création (récent d'abord) ou par catégorie\n- **Persistance locale** : les notes sont sauvegardées dans le téléphone\n\n### 2. Composants obligatoires\n\n- **NoteCard** : carte de note avec titre, aperçu du contenu, catégorie et date\n- **CategoryFilter** : barre horizontale de filtres par catégorie\n- **NoteEditor** : écran de création/édition avec formulaire validé\n- **EmptyState** : état vide avec illustration quand il n'y a pas de notes\n- **SearchBar** : barre de recherche animée\n\n### 3. Écrans\n\n- **Accueil** : liste des notes avec filtres et recherche\n- **Édition** : formulaire de création/édition de note\n- **Détails** : lecture complète d'une note\n\n### 4. Navigation et État\n\n- **GoRouter** pour la navigation entre les écrans\n- **Provider** pour la gestion d'état globale du catalogue de notes\n- **TextEditingController** avec dispose() correct dans le formulaire\n\n### 5. Fonctionnalités bonus (optionnelles)\n\n- Thème sombre / clair\n- Notes favorites (étoile)\n- Export des notes en texte\n- Widget d'accueil avec les notes récentes\n\n## Contraintes techniques\n\n- **Flutter 3.19+** avec Dart (null safety)\n- **Material Design 3** (useMaterial3: true)\n- **Provider** pour la gestion d'état\n- **GoRouter** pour la navigation\n- **Package http** pour les appels API (si applicable)\n- **Validation** des formulaires avec Form + TextFormField\n- Les fichiers doivent être séparés dans `lib/` (models, screens, services, widgets)\n\n## Critères d'évaluation\n\n- **Fonctionnalités** : CRUD complet, catégories, recherche, tri et persistance fonctionnels\n- **UI/UX** : Material 3, design cohérent, indicateurs de chargement, état vide\n- **Formulaires** : validation correcte, gestion de TextEditingController\n- **Architecture** : séparation en dossiers, Provider utilisé correctement, code Dart propre\n- **Navigation** : GoRouter configuré, passage de paramètres, retour arrière",
  "evaluationCriteria": [
    "Fonctionnalités : CRUD complet, catégories, recherche, tri et persistance locale fonctionnels",
    "UI/UX : Material 3 appliqué, design cohérent, indicateurs de chargement, état vide géré",
    "Formulaires : validation avec Form, TextFormField, gestion correcte des contrôleurs",
    "Architecture : dossiers séparés (models, screens, services, widgets), Provider utilisé correctement",
    "Navigation : GoRouter configuré avec routes nommées, passage de paramètres, retour arrière"
  ]
};

export default project;
