const project = {
  "title": "Architecture Web Serverless sur AWS",
  "instructions": "# Architecture Web Serverless sur AWS\n\n## Objectif\n\nConcevoir et déployer une application web serverless sur AWS en utilisant les services fondamentaux : S3, CloudFront, API Gateway, Lambda et DynamoDB.\n\n## Consignes\n\n### 1. Stockage Frontend avec S3 et CloudFront\n\n- Créer un bucket S3 pour héberger le frontend statique (React, Vue ou HTML/CSS/JS)\n- Activer le versioning S3 pour pouvoir revenir en arrière\n- Bloquer l'accès public au bucket (Bucket Policy + Public Access Block)\n- Configurer le chiffrement SSE-S3\n- Créer une distribution CloudFront liée au bucket S3\n- Générer un certificat SSL via ACM (Certificate Manager) pour le domaine\n- Configurer la redirection HTTP → HTTPS\n\n### 2. API Serverless avec Lambda et API Gateway\n\n- Créer une API Gateway REST API avec intégration Lambda proxy\n- Développer 3 fonctions Lambda (Node.js) :\n  - GET /items — lecture depuis DynamoDB\n  - POST /items — création d'un item\n  - DELETE /items/{id} — suppression d'un item\n- Chaque Lambda utilise une IAM Role avec les permissions DynamoDB minimalisées (principe du moindre privilège)\n- Activer les logs CloudWatch pour chaque Lambda\n\n### 3. Base de données DynamoDB\n\n- Créer une table DynamoDB avec clé de partition (PK) et mode PAY_PER_REQUEST\n- Insérer 5 items de test via AWS CLI\n- Vérifier les données avec aws dynamodb scan\n\n### 4. Sécurité IAM\n\n- Créer un groupe IAM 'developers' avec une policy custom (lecture seule sur S3, Lambda)\n- Créer un user IAM dans le groupe avec credentials programmatiques\n- Activer MFA sur le user\n- Vérifier l'identité avec aws sts get-caller-identity\n\n### 5. Monitoring et Budget\n\n- Créer un CloudWatch Alarm sur les erreurs Lambda (> 5 erreurs en 5 min)\n- Configurer un AWS Budget de 10€/mois avec alerte email à 80%\n- Activer Cost Explorer et analyser les coûts du mois\n\n## Contraintes techniques\n\n- Toute l'infrastructure doit être créée via AWS CLI (pas de console web)\n- Les Lambda doivent être en Node.js 20.x\n- Les credentials ne doivent JAMAIS être codés en dur\n- Chaque ressource doit être taguée (Environment, Project, Team)\n\n## Livrables\n\n1. Scripts CLI documentés pour créer chaque ressource\n2. Code source des 3 Lambda (Node.js)\n3. Configuration IAM complète (users, groups, policies)\n4. README.md avec architecture, diagramme et instructions de déploiement\n5. Capture d'écran de CloudFront + DynamoDB + CloudWatch",
  "evaluationCriteria": [
    "Infrastructure S3/CloudFront fonctionnelle (bucket sécurisé, CDN avec SSL, HTTP→HTTPS redirect)",
    "API Gateway + Lambda opérationnelle (3 routes CRUD, IAM Role minimaliste, logs CloudWatch)",
    "DynamoDB correctement configurée (table PAY_PER_REQUEST, items de test insérés)",
    "Sécurité IAM (groupe developers, user avec MFA, policies least-privilege, pas de credentials en dur)",
    "Monitoring (CloudWatch Alarm Lambda, Budget AWS, Cost Explorer analysé)"
  ]
};

export default project;
