import { Level } from '@prisma/client';

export const awsCloudPractitioner = {
  techSlug: "aws",
  title: "AWS Cloud Practitioner",
  description: "Fondamentaux du cloud AWS, services de base, securite, tarification et bonnes pratiques pour la certification Cloud Practitioner.",
  level: Level.beginner,
  durationMin: 180,
  lessons: [
    {
      "title": "Introduction au Cloud AWS",
      "durationMin": 45,
      "contentMarkdown": "# Introduction au Cloud AWS\n\n## Introduction\n\nAmazon Web Services (AWS) est la plateforme cloud la plus utilisee au monde. Ce module couvre les concepts fondamentaux du cloud computing et les services AWS de base.\n\n---\n\n## 1. Modeles de Cloud Computing\n\n```\nIaaS (Infrastructure as a Service):\n  - Controle sur l'OS, le reseau et le stockage\n  - Exemple: EC2, VPC\n\nPaaS (Platform as a Service):\n  - Gere l'infrastructure sous-jacente\n  - Exemple: Elastic Beanstalk, RDS\n\nSaaS (Software as a Service):\n  - Application complete gere par le fournisseur\n  - Exemple: WorkMail, Chime\n```\n\n---\n\n## 2. Services AWS Fondamentaux\n\n```\nCompute:\n  - EC2: Machines virtuelles\n  - Lambda: Serverless (FaaS)\n  - ECS/EKS: Conteneurs\n\nStockage:\n  - S3: Stockage d'objets\n  - EBS: Stockage par blocs\n  - Glacier: Archivage\n\nBase de donnees:\n  - RDS: Relationnel (MySQL, PostgreSQL)\n  - DynamoDB: NoSQL\n  - ElastiCache: Cache (Redis, Memcached)\n\nReseau:\n  - VPC: Reseau prive virtuel\n  - CloudFront: CDN\n  - Route 53: DNS\n```\n\n---\n\n## 3. Regions et Zones de Disponibilite\n\n```\nRegions AWS (exemples):\n  - us-east-1 (Virginie du Nord)\n  - eu-west-1 (Irlande)\n  - eu-west-3 (Paris)\n  - ap-southeast-1 (Singapour)\n\nAZ (Availability Zones):\n  - Chaque region a 3+ zones\n  - Zones isolees en cas de panne\n  - Connectees par fibre optique\n\nPoints de presence:\n  - 400+ points de presence (Edge Locations)\n  - Utilises par CloudFront et Route 53\n```\n\n---\n\n## 4. Modele de Responsabilite Partagee\n\n```\nAWS est responsable de la SECURITE DU CLOUD:\n  - Centres de donnees physiques\n  - Reseau global\n  - Hyperviseurs\n\nLe client est responsable de la SECURITE DANS LE CLOUD:\n  - Donnees au repos et en transit\n  - Configuration des pare-feux\n  - Gestion des identites (IAM)\n  - Systemes d'exploitation\n\nChiffrement:\n  - AES-256 pour le stockage\n  - TLS 1.2+ pour le transit\n  - KMS pour la gestion des cles\n```",
    },
    {
      "title": "IAM et Securite",
      "durationMin": 45,
      "contentMarkdown": "# IAM et Securite\n\n## Introduction\n\nAWS Identity and Access Management (IAM) permet de gerer les acces aux services AWS de maniere securisee. C'est le fondement de la securite sur AWS.\n\n---\n\n## 1. Utilisateurs et Groupes IAM\n\n```json\n// Exemple de politique IAM\n{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:ListBucket\",\n        \"s3:GetObject\"\n      ],\n      \"Resource\": [\n        \"arn:aws:s3:::mon-bucket\",\n        \"arn:aws:s3:::mon-bucket/*\"\n      ]\n    }\n  ]\n}\n```\n\n```bash\n# Creer un utilisateur\naws iam create-user --user-name devops-user\n\n# Attacher une politique\naws iam attach-user-policy \\\n  --user-name devops-user \\\n  --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess\n\n# Creer un groupe\naws iam create-group --group-name developers\naws iam add-user-to-group --group-name developers --user-name devops-user\n```\n\n---\n\n## 2. Roles IAM\n\n```json\n// Politique de confiance pour un role EC2\n{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Service\": \"ec2.amazonaws.com\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n```\n\n```bash\n# Creer un role\naws iam create-role \\\n  --role-name EC2-S3-Access \\\n  --assume-role-policy-document file://trust-policy.json\n\n# Attacher une politique au role\naws iam attach-role-policy \\\n  --role-name EC2-S3-Access \\\n  --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess\n```\n\n---\n\n## 3. Politiques et Permissions\n\n```json\n// Principe du moindre privilege\n{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Deny\",\n      \"Action\": \"*\",\n      \"Resource\": \"*\",\n      \"Condition\": {\n        \"Bool\": {\"aws:SecureTransport\": \"false\"}\n      }\n    }\n  ]\n}\n```\n\n**Types de politiques :**\n- AWS Managed : creees par AWS\n- Customer Managed : creees par vous\n- Inline : attachees directement a un utilisateur/role\n\n---\n\n## 4. Bonnes Pratiques IAM\n\n```\n1. Activer MFA pour le compte root\n2. Utiliser des roles plutot que des cles d'acces\n3. Principe du moindre privilege\n4. Auditer regulierement avec IAM Access Analyzer\n5. Utiliser des politiques basees sur les ressources\n6. Rotation reguliere des cles d'acces\n7. Ne jamais partager les cles d'acces\n8. Utiliser AWS Organizations pour la gestion multi-comptes\n```",
    },
    {
      "title": "Stockage et Base de Donnees",
      "durationMin": 45,
      "contentMarkdown": "# Stockage et Base de Donnees\n\n## Introduction\n\nAWS propose de nombreuses solutions de stockage et de base de donnees adaptees a differents cas d'usage, du stockage d'objets aux bases relationnelles et NoSQL.\n\n---\n\n## 1. Amazon S3\n\n```bash\n# Creer un bucket\naws s3 mb s3://mon-bucket-unique\n\n# Uploader un fichier\naws s3 cp fichier.txt s3://mon-bucket-unique/\n\n# Classes de stockage\naws s3 cp fichier.txt s3://mon-bucket-unique/ \\\n  --storage-class STANDARD_IA\n\n# Versionnement\naws s3api put-bucket-versioning \\\n  --bucket mon-bucket-unique \\\n  --versioning-configuration Status=Enabled\n\n# Cycle de vie\naws s3api put-bucket-lifecycle-configuration \\\n  --bucket mon-bucket-unique \\\n  --lifecycle-configuration file://lifecycle.json\n```\n\n---\n\n## 2. Amazon RDS\n\n```bash\n# Creer une instance PostgreSQL\naws rds create-db-instance \\\n  --db-instance-identifier ma-base \\\n  --db-instance-class db.t3.micro \\\n  --engine postgres \\\n  --master-username admin \\\n  --master-user-password password123 \\\n  --allocated-storage 20\n\n# Creer un read replica\naws rds create-db-instance-read-replica \\\n  --db-instance-identifier ma-base-replica \\\n  --source-db-instance-identifier ma-base\n\n# Multi-AZ pour la haute disponibilite\naws rds modify-db-instance \\\n  --db-instance-identifier ma-base \\\n  --multi-az\n```\n\n---\n\n## 3. Amazon DynamoDB\n\n```bash\n# Creer une table NoSQL\naws dynamodb create-table \\\n  --table-name Utilisateurs \\\n  --attribute-definitions AttributeName=id,AttributeType=S \\\n  --key-schema AttributeName=id,KeyType=HASH \\\n  --billing-mode PAY_PER_REQUEST\n\n# Inserer des donnees\naws dynamodb put-item \\\n  --table-name Utilisateurs \\\n  --item '{\n    \"id\": {\"S\": \"user123\"},\n    \"nom\": {\"S\": \"Alice\"},\n    \"email\": {\"S\": \"alice@example.com\"}\n  }'\n\n# Interroger la table\naws dynamodb query \\\n  --table-name Utilisateurs \\\n  --key-condition-expression \"id = :id\" \\\n  --expression-attribute-values '{\":id\": {\"S\": \"user123\"}}'\n```\n\n---\n\n## 4. Comparaison des Services\n\n```\nS3:\n  - Stockage d'objets\n  - 99.999999999% de durabilite\n  - Ideal pour fichiers, images, backups\n\nEBS:\n  - Stockage par blocs pour EC2\n  - Snapshots pour backup\n  - Differents types: gp3, io2, st1\n\nRDS:\n  - Base relationnelle geree\n  - MySQL, PostgreSQL, Oracle, SQL Server\n  - Multi-AZ, Read Replicas\n\nDynamoDB:\n  - NoSQL serverless\n  - Latence milliseconde\n  - Auto-scaling\n  - Ideal pour applications web\n```",
    },
    {
      "title": "Tarification et Support",
      "durationMin": 45,
      "contentMarkdown": "# Tarification et Support\n\n## Introduction\n\nAWS propose un modele de tarification a l'utilisation (pay-as-you-go) avec plusieurs outils pour estimer et optimiser les couts.\n\n---\n\n## 1. Modeles de Tarification\n\n```\nPay-as-you-go:\n  - Payer uniquement ce que vous utilisez\n  - Pas d'engagement a long terme\n  - Ideal pour les charges de travail variables\n\nSavings Plans:\n  - Engagement 1 ou 3 ans\n  - Jusqu'a 72% d'economie\n  - Flexible entre les services\n\nReserved Instances:\n  - Engagement 1 ou 3 ans\n  - Jusqu'a 75% d'economie\n  - Standard ou convertible\n\nSpot Instances:\n  - Jusqu'a 90% d'economie\n  - Instances interrompables\n  - Ideal pour les batchs et tests\n```\n\n---\n\n## 2. AWS Pricing Calculator\n\n```\n1. Aller sur https://calculator.aws\n2. Ajouter les services necessaires\n3. Configurer:\n   - Region\n   - Type d'instance\n   - Stockage\n   - Transfert de donnees\n4. Generer l'estimation\n5. Partager ou exporter l'estimation\n\nExemple d'estimation:\n  - 2 x t3.medium (24/7) = ~$70/mois\n  - 100GB S3 Standard = ~$2.30/mois\n  - 20GB RDS PostgreSQL = ~$50/mois\n  - Total estime: ~$122.30/mois\n```\n\n---\n\n## 3. AWS Cost Explorer\n\n```bash\n# Activer Cost Explorer (Console)\n# Outils disponibles:\n#   - Cout par service\n#   - Cout par compte\n#   - Previsions de cout\n#   - Recommendations d'optimisation\n\n# Budgets AWS\naws budgets create-budget \\\n  --account-id 123456789012 \\\n  --budget file://budget.json \\\n  --notifications-with-subscribers file://notifications.json\n\n# Exemple de budget\n{\n  \"BudgetName\": \"Budget-Mensuel\",\n  \"BudgetLimit\": {\"Amount\": \"1000\", \"Unit\": \"USD\"},\n  \"TimeUnit\": \"MONTHLY\",\n  \"BudgetType\": \"COST\"\n}\n```\n\n---\n\n## 4. Plans de Support\n\n```\nSupport Basic (inclus):\n  - Ressources en libre-service\n  - AWS Personal Health Dashboard\n  - Documentation et forums\n\nSupport Developer ($29/mois):\n  - Support par email\n  - Reponse < 24h\n  - Guide general\n\nSupport Business ($100/mois):\n  - Support 24/7 par chat et telephone\n  - Reponse < 1h (critique)\n  - AWS Trusted Advisor\n\nSupport Enterprise ($15k+):\n  - TAM dedie (Technical Account Manager)\n  - Reponse < 15min (critique)\n  - Concierge Support Team\n  - Well-Architected Reviews\n```",
    },
  ],
};